version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: development
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 1
    groups:
      ci-actions:
        patterns:
          - "*"

  - package-ecosystem: gradle
    directory: /
    target-branch: development
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 1
    groups:
      android-and-kotlin:
        patterns:
          - "*"

  - package-ecosystem: bundler
    directory: /
    target-branch: development
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 1
    groups:
      release-tooling:
        patterns:
          - "*"
